import { useEffect, useState } from "react";
import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Music from '../../assets/music.jpg';
import Image from "next/image";


const AllLyrics: NextPage = () => {
    const [data, setdata] = useState([]);
    const getData = async () => {
        try {
            const res = await axios({
                method: "GET",
                url: "https://www.alldesilyrics.com/wp-json/wp/v2/posts",
            });

            if (res && res.data) {
                setdata(res.data);
            }
            console.log("response", res.data);
        } catch (error) {
            console.log(error);
        }
    };

    useEffect(() => {
        getData();
    }, []);
    return (
        <>
            <Head>
                <title>All Songs Lyrics</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/*  */}
            <div className="mt-10">
						<div className="mt-6 grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
                    {data.map((value: any) => {
                        return (
                            <div key={value.title} className="pt-6">
                                <div className="flow-root bg-light rounded-lg px-4 pb-8">
                                    <div className="-mt-6">
                                        <div className="flex items-center justify-center">
                                            <span className="p-2">
                                            <Image src={Music} alt='music' className="rounded w-9/12 m-auto"/>

                                            </span>
                                        </div>
                                        <div className="text-center justify-center items-center">
                                            <h3 className="mt-4 text-lg font-bold w-full break-words overflow-x-auto text-primary tracking-tight">
                                            {value.title.rendered.replace(/[^a-zA-Z ]/g, " ")}

                                            </h3>
                                            <span className="mt-2 text-sm text-secondary block">
                                            {value.title.rendered.replace(/[^a-zA-Z ]/g, " ")}

                                            </span>
                                            {/* <p className="leading-relaxed mb-3"
                                                    key={value.id}
                                                    dangerouslySetInnerHTML={{ __html: value.content.rendered }}>
                                                </p> */}
                                            <button
                                                className="mt-5 text-md text-active"
                                                // onClick={() => {
                                                //     getLyrics(song.result.id);
                                                // }}
                                            >
                                                Get Lyrics &rarr;
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        );
                    })}
						</div>
					</div>

            {/*  */}

            {/* <section className="text-gray-600 body-font">
                <div className="container px-5 py-24 mx-auto">
                    <div className="flex flex-wrap -m-4">
                        {data.map((value: any) => {
                            return (
                                <>
                                    <div className="p-4 md:w-1/3">
                                        <div className="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">


                                            <Image src={Music} alt='music' />

                                            <div className="p-6">
                                                <h2 className="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">
                                                    Mix
                                                </h2>
                                                <h1 className="title-font font-bold text-lg font-medium text-gray-900 mb-3">
                                                    {value.title.rendered.replace(/[^a-zA-Z ]/g, " ")}
                                                </h1>
                                                <p className="leading-relaxed mb-3"
                                                    key={value.id}
                                                    dangerouslySetInnerHTML={{ __html: value.content.rendered }}>
                                                </p>
                                                <div className="flex items-center flex-wrap ">
                                                    <a className="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0">
                                                        Learn More
                                                        <svg
                                                            className="w-4 h-4 ml-2"
                                                            viewBox="0 0 24 24"
                                                            stroke="currentColor"
                                                            strokeWidth={2}
                                                            fill="none"
                                                            strokeLinecap="round"
                                                            strokeLinejoin="round"
                                                        >
                                                            <path d="M5 12h14" />
                                                            <path d="M12 5l7 7-7 7" />
                                                        </svg>
                                                    </a>
                                                    <span className="text-gray-400 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm pr-3 py-1 border-r-2 border-gray-200">
                                                        <svg
                                                            className="w-4 h-4 mr-1"
                                                            stroke="currentColor"
                                                            strokeWidth={2}
                                                            fill="none"
                                                            strokeLinecap="round"
                                                            strokeLinejoin="round"
                                                            viewBox="0 0 24 24"
                                                        >
                                                            <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" />
                                                            <circle cx={12} cy={12} r={3} />
                                                        </svg>
                                                        1.2K
                                                    </span>
                                                    <span className="text-gray-400 inline-flex items-center leading-none text-sm">
                                                        <svg
                                                            className="w-4 h-4 mr-1"
                                                            stroke="currentColor"
                                                            strokeWidth={2}
                                                            fill="none"
                                                            strokeLinecap="round"
                                                            strokeLinejoin="round"
                                                            viewBox="0 0 24 24"
                                                        >
                                                            <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z" />
                                                        </svg>
                                                        6
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </>
                            );
                        })}
                    </div>
                </div>
            </section> */}
        </>
    );
};

export default AllLyrics;